# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='state_transfer.proto',
  package='state_transfer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14state_transfer.proto\x12\x0estate_transfer\"\xc0\x01\n\x06Update\x12\x11\n\trow_index\x18\x01 \x01(\x03\x12\x15\n\rpkey_col_name\x18\x02 \x01(\t\x12\x10\n\x08pkey_val\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12.\n\x07op_type\x18\x05 \x01(\x0e\x32\x1d.state_transfer.Update.OpType\x12\r\n\x05txnId\x18\x06 \x01(\x03\",\n\x06OpType\x12\n\n\x06UPDATE\x10\x00\x12\n\n\x06INSERT\x10\x01\x12\n\n\x06REMOVE\x10\x02\"V\n\tUpdateReq\x12\x10\n\x08shard_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x63ol_id\x18\x02 \x01(\t\x12\'\n\x07updates\x18\x03 \x03(\x0b\x32\x16.state_transfer.Update\"\x19\n\nUpdateResp\x12\x0b\n\x03res\x18\x01 \x01(\x05\":\n\x07TxnInfo\x12\r\n\x05txnId\x18\x01 \x01(\x03\x12\x0f\n\x07TxnType\x18\x02 \x01(\x05\x12\x0f\n\x07isQuery\x18\x03 \x01(\x08\"V\n\x05Order\x12\x0e\n\x06txn_id\x18\x01 \x01(\x03\x12\x10\n\x08txn_type\x18\x02 \x01(\x03\x12\x14\n\x0ctouched_cols\x18\x03 \x03(\t\x12\x15\n\rtouched_shard\x18\x04 \x03(\x05\"C\n\x08OrderReq\x12\x10\n\x08shard_id\x18\x01 \x01(\x05\x12%\n\x06orders\x18\x02 \x03(\x0b\x32\x15.state_transfer.Order\"\x18\n\tOrderResp\x12\x0b\n\x03res\x18\x01 \x01(\x05\"g\n\x05Query\x12\x0e\n\x06txn_id\x18\x01 \x01(\x03\x12\x10\n\x08txn_type\x18\x02 \x01(\x03\x12\x14\n\x0ctouched_cols\x18\x03 \x03(\t\x12\x15\n\rtouched_shard\x18\x04 \x03(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\"\x18\n\tQueryResp\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32\xee\x01\n\nOLAPServer\x12M\n\x0eTransferUpdate\x12\x19.state_transfer.UpdateReq\x1a\x1a.state_transfer.UpdateResp\"\x00(\x01\x30\x01\x12J\n\rTransferOrder\x12\x18.state_transfer.OrderReq\x1a\x19.state_transfer.OrderResp\"\x00(\x01\x30\x01\x12\x45\n\x0bSubmitQuery\x12\x15.state_transfer.Query\x1a\x19.state_transfer.QueryResp\"\x00(\x01\x30\x01\x62\x06proto3'
)



_UPDATE_OPTYPE = _descriptor.EnumDescriptor(
  name='OpType',
  full_name='state_transfer.Update.OpType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INSERT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REMOVE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=189,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_UPDATE_OPTYPE)


_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='state_transfer.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_index', full_name='state_transfer.Update.row_index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pkey_col_name', full_name='state_transfer.Update.pkey_col_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pkey_val', full_name='state_transfer.Update.pkey_val', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='state_transfer.Update.value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='op_type', full_name='state_transfer.Update.op_type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txnId', full_name='state_transfer.Update.txnId', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _UPDATE_OPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=233,
)


_UPDATEREQ = _descriptor.Descriptor(
  name='UpdateReq',
  full_name='state_transfer.UpdateReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='state_transfer.UpdateReq.shard_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='col_id', full_name='state_transfer.UpdateReq.col_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updates', full_name='state_transfer.UpdateReq.updates', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=321,
)


_UPDATERESP = _descriptor.Descriptor(
  name='UpdateResp',
  full_name='state_transfer.UpdateResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='state_transfer.UpdateResp.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=348,
)


_TXNINFO = _descriptor.Descriptor(
  name='TxnInfo',
  full_name='state_transfer.TxnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='txnId', full_name='state_transfer.TxnInfo.txnId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TxnType', full_name='state_transfer.TxnInfo.TxnType', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isQuery', full_name='state_transfer.TxnInfo.isQuery', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=408,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='state_transfer.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='txn_id', full_name='state_transfer.Order.txn_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txn_type', full_name='state_transfer.Order.txn_type', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='touched_cols', full_name='state_transfer.Order.touched_cols', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='touched_shard', full_name='state_transfer.Order.touched_shard', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=496,
)


_ORDERREQ = _descriptor.Descriptor(
  name='OrderReq',
  full_name='state_transfer.OrderReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='state_transfer.OrderReq.shard_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orders', full_name='state_transfer.OrderReq.orders', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=565,
)


_ORDERRESP = _descriptor.Descriptor(
  name='OrderResp',
  full_name='state_transfer.OrderResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='state_transfer.OrderResp.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=591,
)


_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='state_transfer.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='txn_id', full_name='state_transfer.Query.txn_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txn_type', full_name='state_transfer.Query.txn_type', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='touched_cols', full_name='state_transfer.Query.touched_cols', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='touched_shard', full_name='state_transfer.Query.touched_shard', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='state_transfer.Query.content', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=696,
)


_QUERYRESP = _descriptor.Descriptor(
  name='QueryResp',
  full_name='state_transfer.QueryResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res', full_name='state_transfer.QueryResp.res', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=722,
)

_UPDATE.fields_by_name['op_type'].enum_type = _UPDATE_OPTYPE
_UPDATE_OPTYPE.containing_type = _UPDATE
_UPDATEREQ.fields_by_name['updates'].message_type = _UPDATE
_ORDERREQ.fields_by_name['orders'].message_type = _ORDER
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
DESCRIPTOR.message_types_by_name['UpdateReq'] = _UPDATEREQ
DESCRIPTOR.message_types_by_name['UpdateResp'] = _UPDATERESP
DESCRIPTOR.message_types_by_name['TxnInfo'] = _TXNINFO
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['OrderReq'] = _ORDERREQ
DESCRIPTOR.message_types_by_name['OrderResp'] = _ORDERRESP
DESCRIPTOR.message_types_by_name['Query'] = _QUERY
DESCRIPTOR.message_types_by_name['QueryResp'] = _QUERYRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.Update)
  })
_sym_db.RegisterMessage(Update)

UpdateReq = _reflection.GeneratedProtocolMessageType('UpdateReq', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQ,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.UpdateReq)
  })
_sym_db.RegisterMessage(UpdateReq)

UpdateResp = _reflection.GeneratedProtocolMessageType('UpdateResp', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESP,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.UpdateResp)
  })
_sym_db.RegisterMessage(UpdateResp)

TxnInfo = _reflection.GeneratedProtocolMessageType('TxnInfo', (_message.Message,), {
  'DESCRIPTOR' : _TXNINFO,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.TxnInfo)
  })
_sym_db.RegisterMessage(TxnInfo)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.Order)
  })
_sym_db.RegisterMessage(Order)

OrderReq = _reflection.GeneratedProtocolMessageType('OrderReq', (_message.Message,), {
  'DESCRIPTOR' : _ORDERREQ,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.OrderReq)
  })
_sym_db.RegisterMessage(OrderReq)

OrderResp = _reflection.GeneratedProtocolMessageType('OrderResp', (_message.Message,), {
  'DESCRIPTOR' : _ORDERRESP,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.OrderResp)
  })
_sym_db.RegisterMessage(OrderResp)

Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.Query)
  })
_sym_db.RegisterMessage(Query)

QueryResp = _reflection.GeneratedProtocolMessageType('QueryResp', (_message.Message,), {
  'DESCRIPTOR' : _QUERYRESP,
  '__module__' : 'state_transfer_pb2'
  # @@protoc_insertion_point(class_scope:state_transfer.QueryResp)
  })
_sym_db.RegisterMessage(QueryResp)



_OLAPSERVER = _descriptor.ServiceDescriptor(
  name='OLAPServer',
  full_name='state_transfer.OLAPServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=725,
  serialized_end=963,
  methods=[
  _descriptor.MethodDescriptor(
    name='TransferUpdate',
    full_name='state_transfer.OLAPServer.TransferUpdate',
    index=0,
    containing_service=None,
    input_type=_UPDATEREQ,
    output_type=_UPDATERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TransferOrder',
    full_name='state_transfer.OLAPServer.TransferOrder',
    index=1,
    containing_service=None,
    input_type=_ORDERREQ,
    output_type=_ORDERRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitQuery',
    full_name='state_transfer.OLAPServer.SubmitQuery',
    index=2,
    containing_service=None,
    input_type=_QUERY,
    output_type=_QUERYRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OLAPSERVER)

DESCRIPTOR.services_by_name['OLAPServer'] = _OLAPSERVER

# @@protoc_insertion_point(module_scope)
