
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s0:8000", "s1:8001", "s2:8002"]
    - ["s3:8100", "s4:8101", "s5:8102"]
    - ["s6:8200", "s7:8201", "s8:8202"]
    - ["s9:8300", "s10:8301", "s11:8302"]
  client: # each line is a partition
    - ["c1", "c5", "c9"]
    - ["c2", "c6"]
    - ["c3", "c7"]
    - ["c4", "c8"]
# site_name - process_name map
process:
  s0: S1
  s1: S1
  s2: S1
  s3: S2
  s4: S2
  s5: S2
  s6: S3
  s7: S3
  s8: S3
  s9: S4
  s10: S4
  s11: S4
  c1: C1
  c2: C2
  c3: C3
  c4: C4
  c5: C1
  c6: C2
  c7: C3
  c8: C4
  

host:
  S1: 10.22.1.7
  S2: 10.22.1.17
  S3: 10.22.1.18
  S4: 10.22.1.7
  C1: 10.22.1.7
  C2: 10.22.1.17
  C3: 10.22.1.18
  C4: 10.22.1.7

# reused as region
datacenter:
  10.22.1.7: dc1
  10.22.1.17: dc2
  10.22.1.18: dc3

#ocean-vista paramaters

ovparams:
  aggregate_interval_ms: 5
  gossip_interval_ms: 10
  clock_drift_ms: 5  # to differentiate processes on the same host, they will drifted by (-x, x), set to 0 if site on different servers

edgeconfig:
  edge_deployment : True
  client_in_region_rate: 100 # percentage of clients reside in its home region (datacenter id)

chronosparams:
  local_sync_interval_ms: 10
